server:
  port: 8001
  context-path: /wsapi01
spring:
  application:
    name: WeStartServiceApi01
  redis:
    host: 10.51.92.132
    port: 6379
    password: HJ8q2PNY5x)nmLiZ5kLJs+(w9J(&bHPROhvXn-
  datasource:
    url: jdbc:mysql://10.51.92.132:3306/westar_test?characterEncoding=UTF-8&amp;amp;autoReconnect=true&amp;amp;failOverReadOnly=false
    username: wear
    password: 3eWoKQsVjg
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
      discovery:
        register: true
logging:
  level:
    root: info
application:
  blow:
    key: wangab@123